### ISSUE TITLE
Define a schema for the output

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/runner#11]

**Comment by cmungall** [comment]
I ran the output through linkml-model-enrichment:

```yaml
id: https://w3id.org/example
name: example
description: example
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  example: https://w3id.org/example
default_prefix: example
types:
  biolink identifier:
    typeof: string
  identifier:
    typeof: string
classes:
  example:
    slots:
    - document id
    - type
    - start position
    - end position
    - matched term
    - preferred form
    - entity id
    - origin
    - sentence
    slot_usage: {}
slots:
  document id:
    range: integer
    examples:
    - value: '507072'
  type:
    range: biolink identifier
    examples:
    - value: biolink:organismalentity
  start position:
    range: integer
    examples:
    - value: '18591'
  end position:
    range: integer
    examples:
    - value: '18594'
  matched term:
    range: string
    examples:
    - value: all
  preferred form:
    range: string
    examples:
    - value: root
  entity id:
    range: identifier
    examples:
    - value: ncbitaxon:1_synonym
  origin:
    examples:
    - value: ecocore.json
  sentence:
    range: string
```
